package org.khorum.oss.konstellation.metaDsl.annotation

/**
 * Annotation to mark classes that are generated by the DSL processor.
 *
 * @param name The name of the generated DSL class - defaults to the class name.
 * @param debug Whether to enable debug logging.
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.SOURCE)
annotation class GeneratedDsl(
    val name: String = "",
    val debug: Boolean = false
)
