package org.khorum.oss.konstellation.metaDsl.annotation

/**
 * Annotation to mark classes that are generated by the DSL processor.
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.SOURCE)
annotation class GeneratedDsl(
    @Deprecated("Use ListDsl instead")
    val withListGroup: Boolean = false,
    @Deprecated("Use MapDsl instead")
    val withMapGroup: String = MapGroupTypes.NONE,
    @Deprecated("Use RootDsl instead")
    val isRoot: Boolean = false,
    val debug: Boolean = false
) {
    /**
     * Constants representing the different types of map groups.
     */
    object MapGroupTypes {
        const val NONE = "NONE"
        const val SINGLE = "SINGLE"
        const val LIST = "LIST"
        const val ALL = "ALL"
    }
}
